language: node_js
node_js:
- '4'
- '6'
sudo: false
cache:
  directories:
  - node_modules
after_success: |
  echo "TRAVIS_NODE_VERSION=${TRAVIS_NODE_VERSION}"
deploy:
  provider: npm
  email: lukas.pustina@gmail.com
  api_key:
    secure: i3n7ZS1e4TO2fvya94vanigRNCCG3QrTW7aFpV+jZTpgSRUyPIHpgTfLZezRhi8JUggKwp0dHWOrZEFBXJcjnANs2h1z7WgSKT/67toMntR2q8ezde/G2hfT31lmcDTBVjbmYQ57FcAtAZCRD5/F5kndbh8qYk59Hh0VpcBUJytUfb2oJJnAZNRUdYBAB6AOyOe9chaNYXISHVmiHDVhIup6vcc2v2ufwOT7xtNzQPqyu1YZoCBvJMagbAAILZzkPvUBapGoU2/7u93a0KpELvgp1pbWJzpo3tiftG3wxLPjfm+uRHosQ1nRXAqYFwpK7oc79gIzHxJtkr50ASL1L3MuboQyxCwDI10Q9Sle1hOhcffF2Fx6b9wW2dr+PS/gpJaWvvugr2Q9EXxqYaQ15kht8kv4oqzdlNjuoL3nxRTE5/z2ZDtgLy96sF7bVMRQX8WodWJGnV+441gzcIsFf3QwouiyP9J7TxlD2TpZz2OQj7dAQ5oMYFbFc5ew2ZiOV8riBwGSNtDbKTwIFa9yuMZBtQLolMujM71QDAWBqPpDb1IZ1Vr1uUFe+0oecwaD6gPzsboa/teUo6NYB6xz0gFbUxWxCQSAEzBxHDSU2pTVNROENXh8YC5vZv8hFqwwkqnhWxH0OF9V1SaXU/6XB/nCoasdbBxuurDku9b5LxI=
  on:
    tags: true
    condition:
    - $TRAVIS_NODE_VERSION == 4
    repo: lukaspustina/hubot-bangbang
